function(qbox_collect_test_executables directory output_variable)
    set(executables "")
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(target_type "${target}" TYPE)
        if(target_type STREQUAL "EXECUTABLE")
            list(APPEND executables "${target}")
        endif()
    endforeach()
    get_property(subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(subdirectory IN LISTS subdirectories)
        qbox_collect_test_executables("${subdirectory}" child_executables)
        list(APPEND executables ${child_executables})
    endforeach()
    set(${output_variable} "${executables}" PARENT_SCOPE)
endfunction()

function(qbox_add_selected_test_directories source_root binary_root output_variable)
    get_filename_component(source_root "${source_root}" REALPATH)
    set(selected_dirs "")
    foreach(test_dir IN LISTS ARGN)
        if(IS_ABSOLUTE "${test_dir}")
            message(FATAL_ERROR
                "QBOX_CORE_TEST_DIRS entries must be relative to qbox/tests: ${test_dir}")
        endif()
        file(TO_CMAKE_PATH "${test_dir}" normalized_test_dir)
        if(normalized_test_dir MATCHES "(^|/)\\.\\.(/|$)")
            message(FATAL_ERROR
                "QBOX_CORE_TEST_DIRS entries must not contain '..': ${test_dir}")
        endif()

        set(test_source_dir "${source_root}/${normalized_test_dir}")
        if(NOT EXISTS "${test_source_dir}/CMakeLists.txt")
            message(FATAL_ERROR
                "QBOX core test directory does not exist: ${normalized_test_dir}")
        endif()
        get_filename_component(test_source_dir "${test_source_dir}" REALPATH)
        file(RELATIVE_PATH normalized_test_dir "${source_root}" "${test_source_dir}")
        if(normalized_test_dir MATCHES "^\\.\\.(/|$)")
            message(FATAL_ERROR
                "QBOX core test directory escapes qbox/tests: ${test_dir}")
        endif()

        foreach(selected_dir IN LISTS selected_dirs)
            if(normalized_test_dir STREQUAL selected_dir)
                message(FATAL_ERROR
                    "QBOX_CORE_TEST_DIRS contains a duplicate: ${normalized_test_dir}")
            endif()
            string(FIND "${normalized_test_dir}" "${selected_dir}/" selected_prefix)
            string(FIND "${selected_dir}" "${normalized_test_dir}/" test_prefix)
            if(selected_prefix EQUAL 0 OR test_prefix EQUAL 0)
                message(FATAL_ERROR
                    "QBOX_CORE_TEST_DIRS entries overlap: ${selected_dir} and ${normalized_test_dir}")
            endif()
        endforeach()
        list(APPEND selected_dirs "${normalized_test_dir}")
    endforeach()

    foreach(test_dir IN LISTS selected_dirs)
        add_subdirectory("${source_root}/${test_dir}" "${binary_root}/${test_dir}")
    endforeach()
    qbox_collect_test_executables("${binary_root}" selected_targets)
    set(${output_variable} "${selected_targets}" PARENT_SCOPE)
endfunction()
